/**
 * KIDS — the pool behind the KIDS difficulty.
 *
 * The bar is a five-to-seven year old, on both ends of the game: they have to
 * be able to DRAW it with a crayon, and the rest of the room has to name it
 * from that drawing. Two rules do most of the filtering:
 *
 *   1. It is in a small child's spoken vocabulary. "cantaloupe", "persimmon"
 *      and "brussels sprout" are perfectly good pictionary words, and they are
 *      not these words — they moved to the normal tier (see medium3.ts).
 *   2. Its drawing is not a coin flip with some other word's drawing. A pie and
 *      a tart, chips and french fries, a courgette and a cucumber all read as
 *      the same scribble, so only the one a child would actually say survives.
 *
 * Plain a-z, one or two words, per isPlayable() in ../words.ts.
 */
export const EASY: string[] = [
  // fruit
  "apple", "banana", "orange", "pear", "peach", "plum", "strawberry",
  "blueberry", "raspberry", "blackberry", "cherry", "grapes", "lemon",
  "lime", "pineapple", "coconut", "mango", "kiwi", "melon", "watermelon",
  // vegetables
  "carrot", "potato", "tomato", "onion", "garlic", "broccoli",
  "cauliflower", "cabbage", "lettuce", "celery", "cucumber", "pumpkin",
  "corn", "peas", "green beans", "bell pepper", "chili pepper", "mushroom",
  "avocado", "pickle",
  // nuts
  "peanut", "acorn",
  // food
  "pizza", "pizza slice", "burger", "cheeseburger", "hotdog", "taco",
  "burrito", "sandwich", "toast", "bread", "baguette", "bagel",
  "croissant", "pretzel", "donut", "cookie", "cake", "birthday cake",
  "cupcake", "muffin", "pie", "apple pie", "pancake", "waffle",
  "gingerbread man", "gingerbread house", "ice cream", "popsicle",
  "milkshake", "chocolate", "chocolate bar", "candy", "lollipop",
  "jelly bean", "marshmallow", "gummy bear", "candy cane", "cotton candy",
  "honey", "honey pot", "jam jar", "butter", "cheese", "egg", "fried egg",
  "bacon", "sausage", "meatball", "steak", "chicken leg", "chicken nugget",
  "corn dog", "onion ring", "sushi", "noodles", "spaghetti", "soup",
  "salad", "fruit salad", "cereal", "french fries", "popcorn",
  "hot chocolate", "lemonade", "juice box", "soda can", "milk carton",
  "tea cup", "water bottle", "straw", "ice cube", "cookie jar",
  "lunchbox", "picnic basket",
  // pets and farm
  "dog", "puppy", "cat", "kitten", "rabbit", "bunny", "hamster",
  "hamster wheel", "guinea pig", "goldfish", "turtle", "tortoise", "pony",
  "horse", "donkey", "cow", "calf", "bull", "goat", "sheep", "lamb",
  "pig", "piglet", "chicken", "chicken coop", "rooster", "hen", "chick",
  "duck", "duckling", "duck pond", "goose", "turkey", "llama", "alpaca",
  "hay bale", "cow bell", "horseshoe", "saddle", "bird cage", "dog bone",
  "dog house", "leash", "collar", "pet bowl", "fish tank", "paw print",
  // wild animals
  "lion", "lion cub", "tiger", "tiger cub", "leopard", "cheetah", "bear",
  "bear cub", "polar bear", "panda", "koala", "wolf", "fox", "elephant",
  "baby elephant", "giraffe", "zebra", "rhino", "hippo", "buffalo",
  "moose", "deer", "camel", "kangaroo", "monkey", "gorilla", "chimpanzee",
  "sloth", "anteater", "armadillo", "porcupine", "hedgehog", "raccoon",
  "skunk", "beaver", "otter", "mole", "mouse", "rat", "squirrel",
  "chipmunk", "bat", "meerkat", "reindeer", "walrus",
  // birds
  "bird", "bird nest", "eagle", "hawk", "owl", "crow", "pigeon", "dove",
  "robin", "parrot", "toucan", "woodpecker", "hummingbird", "swan",
  "flamingo", "pelican", "stork", "seagull", "penguin", "ostrich",
  "peacock", "peacock feather",
  // sea life
  "fish", "shark", "whale", "dolphin", "orca", "seal", "sea lion",
  "sea turtle", "octopus", "squid", "jellyfish", "starfish", "seahorse",
  "crab", "hermit crab", "lobster", "shrimp", "clam", "seashell", "coral",
  "stingray", "eel", "swordfish", "pufferfish", "clownfish", "narwhal",
  "goldfish bowl",
  // bugs
  "bee", "beehive", "wasp", "ant", "anthill", "spider", "spider web",
  "tarantula", "scorpion", "butterfly", "moth", "caterpillar", "cocoon",
  "dragonfly", "grasshopper", "cricket", "beetle", "ladybug", "firefly",
  "mosquito", "fly", "worm", "centipede", "snail", "slug",
  "praying mantis", "stick bug",
  // reptiles and dinosaurs
  "snake", "cobra", "python", "rattlesnake", "lizard", "gecko", "iguana",
  "chameleon", "komodo dragon", "crocodile", "alligator", "frog", "toad",
  "tadpole", "salamander", "axolotl", "dinosaur", "tyrannosaurus",
  "triceratops", "stegosaurus", "brontosaurus", "pterodactyl",
  "velociraptor", "dinosaur egg", "dinosaur bone", "fossil",
  // sky and space
  "sun", "moon", "star", "cloud", "rain", "rain cloud", "raindrop",
  "rainbow", "lightning", "snow", "snowflake", "snowman", "snowball",
  "snow fort", "tornado", "sunrise", "sunset", "comet", "shooting star",
  "planet", "earth", "saturn", "space rocket", "spaceship", "space suit",
  "flying saucer", "telescope",
  // outdoors
  "tree", "oak tree", "pine tree", "palm tree", "apple tree", "bamboo",
  "cactus", "bush", "hedge", "flower", "flower crown", "rose", "tulip",
  "daisy", "daisy chain", "sunflower", "lily", "daffodil", "dandelion",
  "clover", "leaf", "leaves", "leaf pile", "branch", "twig", "tree stump",
  "log", "seed", "sprout", "pinecone", "grass", "hay", "haystack",
  "mountain", "hill", "cliff", "cave", "volcano", "desert", "sand dune",
  "beach", "beach towel", "island", "forest", "jungle", "garden", "farm",
  "river", "lake", "pond", "waterfall", "ocean", "wave", "iceberg",
  "rock", "pebble", "sand", "mud", "mud pie", "puddle", "campfire",
  // house
  "house", "cottage", "cabin", "hut", "igloo", "treehouse", "tent",
  "sleeping bag", "castle", "bouncy castle", "tower", "lighthouse",
  "windmill", "barn", "shed", "greenhouse", "garage", "roof", "chimney",
  "door", "window", "curtain", "wall", "brick", "fence", "gate",
  "mailbox", "doorbell", "door mat", "stairs", "elevator", "fireplace",
  "ceiling fan",
  // furniture
  "bed", "bunk bed", "crib", "sofa", "armchair", "chair", "stool",
  "bench", "table", "desk", "shelf", "bookshelf", "drawer", "mirror",
  "rug", "pillow", "pillow fort", "blanket", "hammock", "rocking chair",
  "high chair", "bean bag", "picture frame", "painting", "poster",
  "clock", "grandfather clock", "cuckoo clock", "alarm clock",
  "hourglass", "candle", "chandelier", "lamp", "lantern", "lightbulb",
  "vase", "plant pot", "watering can",
  // kitchen
  "fridge", "oven", "stove", "microwave", "toaster", "kettle", "teapot",
  "blender", "sink", "faucet", "cutting board", "rolling pin", "whisk",
  "spatula", "can opener", "frying pan", "pot", "oven mitt", "apron",
  "fork", "spoon", "knife", "chopsticks", "plate", "bowl", "mug", "cup",
  "glass", "jug", "salt shaker", "napkin", "trash can", "sponge",
  // bathroom
  "toilet", "bathtub", "bubble bath", "shower", "towel", "toothbrush",
  "toothpaste", "tooth fairy", "soap", "shampoo", "comb", "hairbrush",
  "hair dryer", "rubber duck", "toilet paper", "plunger", "bandage",
  "medicine bottle", "thermometer", "tissue box",
  // clothes
  "shirt", "tshirt", "sweater", "hoodie", "jacket", "coat", "raincoat",
  "tie", "bow tie", "scarf", "pants", "jeans", "shorts", "skirt",
  "dress", "overalls", "pajamas", "swimsuit", "underwear", "socks",
  "shoe", "sneaker", "boot", "rain boot", "sandal", "flip flop",
  "slipper", "high heel", "ice skate", "roller skate", "hat", "cap",
  "cowboy hat", "top hat", "helmet", "crown", "tiara", "headband",
  "hair clip", "glove", "mitten", "belt", "button", "zipper", "backpack",
  "handbag", "wallet", "suitcase", "umbrella", "sunglasses", "glasses",
  "goggles", "mask", "wig", "necklace", "bracelet", "earring", "ring",
  "watch",
  // toys and play
  "ball", "beach ball", "balloon", "balloon animal", "kite", "yoyo",
  "marble", "doll", "puppet", "sock puppet", "teddy bear",
  "stuffed animal", "action figure", "toy car", "toy train", "toy robot",
  "toy box", "cardboard box", "rocking horse", "building block",
  "lego brick", "puzzle piece", "jigsaw puzzle", "board game", "dice",
  "playing card", "chess piece", "dominoes", "jump rope", "hula hoop",
  "frisbee", "slingshot", "water gun", "bubble wand", "spinning top",
  "piggy bank", "sandbox", "sandcastle", "swing", "slide", "water slide",
  "seesaw", "monkey bars", "trampoline", "playground", "hopscotch",
  "pinwheel", "paper airplane", "paper boat", "playdough", "sticker",
  "coloring book", "story book", "gold star", "name tag",
  // parties and fairs
  "gift", "gift box", "ribbon bow", "party hat", "party horn",
  "goodie bag", "birthday candle", "confetti", "streamer", "pinata",
  "carved pumpkin", "candy bucket", "face paint", "clown nose",
  "carousel", "ferris wheel", "roller coaster", "bumper car",
  "circus tent", "juggling ball", "tightrope", "lemonade stand",
  // music
  "guitar", "electric guitar", "violin", "piano", "harp", "accordion",
  "drum", "drum set", "tambourine", "cymbals", "xylophone", "maracas",
  "trumpet", "trombone", "tuba", "saxophone", "flute", "recorder",
  "harmonica", "banjo", "ukulele", "microphone", "headphones", "speaker",
  "radio", "music note", "sheet music",
  // tools and chores
  "hammer", "screwdriver", "wrench", "pliers", "saw", "chainsaw", "drill",
  "axe", "nail", "screw", "ruler", "tape measure", "toolbox", "ladder",
  "step stool", "shovel", "rake", "pitchfork", "wheelbarrow", "lawnmower",
  "garden hose", "sprinkler", "broom", "mop", "bucket", "dustpan",
  "vacuum", "feather duster", "rope", "chain", "string", "tape", "glue",
  "paint can", "paint roller", "paintbrush", "spray can", "magnet",
  "flashlight", "battery", "plug", "padlock", "key", "keychain", "hook",
  "scissors",
  // school and screens
  "pencil", "pen", "marker", "crayon", "chalk", "eraser", "sharpener",
  "notebook", "book", "folder", "paper", "envelope", "stamp", "postcard",
  "letter", "newspaper", "magazine", "map", "treasure map", "globe",
  "calendar", "clipboard", "stapler", "paper clip", "thumbtack",
  "rubber band", "sticky note", "highlighter", "school bus", "blackboard",
  "whiteboard", "desk lamp", "abacus", "calculator", "typewriter",
  "printer", "computer", "laptop", "monitor", "computer mouse", "tablet",
  "phone", "smartphone", "camera", "television", "remote control",
  "game controller", "charger",
  // transport
  "car", "sports car", "race car", "go kart", "taxi", "police car",
  "ambulance", "fire truck", "truck", "pickup truck", "tow truck",
  "garbage truck", "monster truck", "food truck", "cement mixer",
  "dump truck", "tractor", "bulldozer", "excavator", "forklift",
  "crane truck", "van", "bus", "train", "steam train", "railroad track",
  "motorcycle", "scooter", "bicycle", "tricycle", "unicycle",
  "skateboard", "wagon", "shopping cart", "stroller", "wheelchair",
  "sled", "sleigh", "snowmobile", "jet ski", "boat", "sailboat",
  "rowboat", "canoe", "kayak", "raft", "ferry", "ship", "cruise ship",
  "pirate ship", "submarine", "airplane", "jet plane", "helicopter",
  "blimp", "parachute", "rocket ship", "space shuttle", "anchor",
  "propeller", "steering wheel", "tire", "wheel", "gas pump",
  "traffic light", "stop sign", "traffic cone", "road", "bridge",
  "tunnel", "crosswalk", "fire hydrant", "street lamp",
  // people and characters
  "baby", "child", "boy", "girl", "man", "woman", "family", "twins",
  "grandma", "grandpa", "king", "queen", "prince", "princess", "knight",
  "wizard", "wizard hat", "witch", "witch hat", "magic wand",
  "crystal ball", "magic lamp", "genie", "flying carpet", "beanstalk",
  "fairy", "elf", "dwarf", "giant", "troll", "goblin", "unicorn",
  "dragon", "mermaid", "pirate", "eye patch", "ninja", "cowboy", "clown",
  "angel", "ghost", "alien", "robot", "monster", "zombie", "vampire",
  "mummy", "skeleton", "superhero", "scarecrow", "nurse", "doctor",
  "dentist", "teacher", "chef", "waiter", "farmer", "soldier", "sailor",
  "pilot", "police officer", "firefighter", "astronaut", "artist",
  "dancer", "singer", "athlete", "referee", "lifeguard", "mail carrier",
  "barber", "mechanic",
  // body and faces
  "eye", "eyes", "eyebrow", "nose", "mouth", "lips", "tongue", "tooth",
  "teeth", "ear", "cheek", "chin", "face", "head", "hair", "ponytail",
  "braid", "beard", "mustache", "neck", "shoulder", "arm", "elbow",
  "hand", "finger", "thumb", "thumbs up", "high five", "fist", "leg",
  "knee", "foot", "toe", "footprint", "handprint", "heart", "brain",
  "bone", "skull", "muscle", "belly", "smile", "frown", "tear",
  "cartwheel",
  // sports
  "soccer ball", "football", "basketball", "baseball", "tennis ball",
  "golf ball", "volleyball", "bowling ball", "bowling pin",
  "baseball bat", "baseball glove", "tennis racket", "badminton racket",
  "shuttlecock", "hockey stick", "hockey puck", "golf club",
  "cricket bat", "boxing glove", "punching bag", "dumbbell", "barbell",
  "goal post", "basketball hoop", "net", "whistle", "stopwatch",
  "scoreboard", "medal", "trophy", "finish line", "hurdle", "surfboard",
  "snowboard", "skis", "ski pole", "swim goggles", "swim cap",
  "life jacket", "diving board", "fishing rod", "fishing net", "target",
  "dart", "dartboard",
  // shapes and signs
  "circle", "square", "triangle", "rectangle", "oval", "diamond shape",
  "star shape", "heart shape", "spiral", "zigzag", "arrow", "cross",
  "checkmark", "question mark", "exclamation mark", "smiley face",
  "sad face", "flag", "checkered flag", "shield", "speech bubble",
  "thought bubble", "peace sign", "dollar sign", "plus sign",
  "minus sign",
  // odds and ends
  "ticket", "coin", "money", "credit card", "treasure chest", "jewel",
  "compass", "binoculars", "magnifying glass", "microscope", "test tube",
  "beaker", "wind chime", "bird feeder", "birdhouse", "bird bath",
  "wishing well", "fire extinguisher", "life ring", "megaphone",
  "walkie talkie", "vending machine", "cash register", "shopping basket",
  "price tag", "shopping bag",
];
