/** HARD, part three. One or two words, never a phrase. */
export const HARD3: string[] = [
  // everyday friction
  "queue jumping", "double parking", "wrong queue", "slow walker",
  "blocked pavement", "closing doors", "missed lift", "wrong floor",
  "held door", "revolving door", "automatic door", "sticky handle",
  "shopping trolley", "wonky wheel", "self checkout", "unexpected item",
  "card declined", "chip and pin", "contactless", "receipt roll",
  "loyalty points", "expiry date", "best before", "reduced sticker",
  "last one left", "wrong size", "return policy", "restocking fee",
  "delivery slot", "missed delivery", "sorry we missed", "pickup point",
  "packaging waste", "bubble wrap", "flat pack", "missing screw",
  "extra parts", "wrong instructions", "assembly required", "wobbly leg",
  "uneven table", "folded napkin", "sticky table", "wet floor",
  "out of order", "closed for cleaning", "under maintenance",
  "temporary closure", "diversion sign", "road works", "cone maze",
  // household life
  "spring clean", "deep clean", "clutter", "junk drawer", "odd sock",
  "sock pairing", "laundry pile", "ironing pile", "dry cleaning",
  "shrunk jumper", "colour run", "static cling", "lint roller",
  "dust bunny", "cobweb", "skirting board", "picture rail", "wonky shelf",
  "damp patch", "peeling paint", "chipped mug", "cracked tile",
  "loose floorboard", "creaky stair", "sticky door", "draughty window",
  "condensation", "blocked gutter", "leaky tap", "dripping tap",
  "blocked sink", "slow drain", "boiler pressure", "radiator bleed",
  "thermostat war", "meter reading", "standing charge", "smart meter",
  "fuse box", "tripped switch", "extension lead", "daisy chain",
  "cable tangle", "remote hunt", "flat batteries", "dead smoke alarm",
  "low battery chirp", "spare key", "key under mat", "locked out",
  // people and manners
  "small talk", "polite nod", "awkward wave", "wrong wave", "double take",
  "eye contact", "avoided gaze", "resting face", "forced smile",
  "nervous laugh", "fake laugh", "polite cough", "throat clear",
  "interrupting", "talking over", "long pause", "dead air",
  "changing subject", "name forgotten", "wrong name", "mispronounced",
  "introduction fumble", "handshake fail", "hug or handshake",
  "cheek kiss", "personal space", "close talker", "loud talker",
  "over sharer", "one upper", "name dropper", "humble brag",
  "backhanded praise", "faint praise", "passive aggressive", "silent treatment",
  "cold shoulder", "peace offering", "olive branch", "apology",
  "half apology", "grudge", "clean slate", "second chance",
  "benefit of doubt", "white lie", "open secret", "inside joke",
  "running joke", "dad joke", "pun", "groan", "eye roll", "facepalm",
  "cringe", "second hand cringe", "awkward silence", "mic drop",
  "slow clap", "standing ovation", "walk of shame", "victory lap",
  // travel and transit
  "wrong platform", "missed stop", "replacement bus", "signal failure",
  "leaves on line", "wrong ticket", "peak fare", "off peak",
  "season ticket", "barrier fail", "tap in", "tap out", "packed carriage",
  "no seats", "priority seat", "bag on seat", "manspreading",
  "loud phone call", "tinny headphones", "eating on train", "lost property",
  "final stop", "night bus", "last train", "taxi surge", "wrong address",
  "sat nav error", "no signal", "one way street", "bus lane", "clamped",
  "parking ticket", "meter expired", "residents only", "double yellow",
  "speed camera", "flash", "points on licence", "mot", "service due",
  "warning light", "check engine", "empty tank", "range anxiety",
  "charging queue", "wrong fuel", "jump start", "tow truck", "hard shoulder",
  // seasons and weather
  "first frost", "black ice", "grit lorry", "snow day", "school closed",
  "wrong leaves", "hosepipe ban", "heat warning", "sun cream",
  "shade seeking", "melting tarmac", "fan on full", "cold shower",
  "duvet swap", "electric blanket", "hot water bottle", "layering",
  "wrong coat", "umbrella inside out", "wet socks", "muddy boots",
  "puddle splash", "windswept hair", "sun in eyes", "glare", "squint",
  "sunset chase", "golden hour", "long shadow", "short day", "dark by four",
  "clocks change", "extra hour", "lost hour", "body clock", "seasonal blues",
  // work and study
  "blank page", "first draft", "final draft", "one more pass",
  "word count", "citation", "bibliography", "plagiarism", "peer review",
  "reading list", "revision", "cramming", "flash cards", "study group",
  "past papers", "mock exam", "exam hall", "silent room", "invigilator",
  "time up", "pens down", "results day", "grade boundary", "resit",
  "group project", "free rider", "unequal split", "last minute",
  "midnight submission", "deadline extension", "printer failure",
  "lost file", "unsaved work", "autosave", "version conflict",
  "track changes", "final version", "final final", "naming nightmare",
  // odds and ends
  "muscle memory", "phantom vibration", "earworm", "brain freeze",
  "deja vu", "false memory", "tip of tongue", "mental block",
  "second wind", "runners high", "post nap fog", "sleep inertia",
  "food coma", "sugar crash", "caffeine jitters", "decision fatigue",
  "analysis paralysis", "choice overload", "buyers remorse",
  "sunk cost", "wishful thinking", "false start", "cold feet",
  "stage fright", "performance anxiety", "imposter feeling",
  "beginners luck", "lucky streak", "losing streak", "close call",
  "near miss", "narrow escape", "lucky break", "bad timing",
  "perfect timing", "coincidence", "small world", "chance meeting",
];
