/** HARD, part four. One or two words, never a phrase. */
export const HARD4: string[] = [
  // trades and how things work
  "load bearing", "dry rot", "damp proof", "cavity wall", "lintel",
  "joist", "rafter", "eaves", "soffit", "flashing", "pointing",
  "render", "screed", "underlay", "skim coat", "feather edge",
  "spirit level", "plumb line", "chalk line", "mitre joint", "butt joint",
  "counter sink", "pilot hole", "wall plug", "masonry bit", "grout line",
  "silicone bead", "expansion gap", "tolerance", "snagging",
  "dust sheet", "masking tape", "cutting in", "second coat", "primer",
  "undercoat", "gloss finish", "matt finish", "brush marks", "roller nap",
  "paint run", "drop cloth", "wet paint", "touch up", "colour match",
  // machines and motion
  "gear ratio", "torque curve", "friction point", "biting point",
  "clutch slip", "engine braking", "hill start", "kangaroo start",
  "stall", "over rev", "red line", "idle", "cold start", "warm up",
  "wheel spin", "traction", "understeer", "oversteer", "drift",
  "aquaplaning", "brake fade", "hand brake", "reverse park",
  "blind spot", "mirror check", "shoulder check", "lane change",
  "merge", "zip merge", "tailgating", "brake check", "phantom jam",
  "stop start", "roundabout", "slip road", "hard shoulder", "contraflow",
  "average speed", "variable limit", "smart motorway", "gantry",
  // money and numbers
  "compound interest", "simple interest", "principal", "amortisation",
  "overdraft", "credit limit", "minimum payment", "balance transfer",
  "credit score", "hard search", "direct debit", "standing order",
  "subscription creep", "free trial", "auto renewal", "cancellation fee",
  "hidden charge", "service charge", "cover charge", "surcharge",
  "dynamic pricing", "surge pricing", "price match", "loss leader",
  "bulk discount", "unit price", "shrinkflation", "skimpflation",
  "inflation", "deflation", "stagnation", "cost of living", "real terms",
  "gross", "net", "margin", "markup", "break even", "cash flow",
  "burn rate", "runway", "valuation", "dilution", "vesting", "buyback",
  "dividend", "yield", "portfolio", "diversification", "hedge",
  "bull market", "bear market", "correction", "bubble", "crash",
  // language and thought
  "double negative", "run on sentence", "oxford comma", "split infinitive",
  "dangling modifier", "mixed metaphor", "malapropism", "spoonerism",
  "tongue twister", "alliteration", "onomatopoeia", "rhyme", "half rhyme",
  "iambic", "haiku", "limerick", "acrostic", "anagram", "palindrome",
  "acronym", "initialism", "portmanteau", "neologism", "loanword",
  "false friend", "cognate", "dialect", "accent", "idiolect", "slang",
  "jargon", "euphemism", "dysphemism", "understatement", "hyperbole",
  "irony", "sarcasm", "satire", "parody", "pastiche", "allegory",
  "metaphor", "simile", "personification", "foreshadowing", "flashback",
  "unreliable narrator", "framing device", "in medias res", "denouement",
  // process and systems
  "critical path", "dependency", "blocker", "bottleneck", "throughput",
  "lead time", "cycle time", "queue depth", "backlog", "triage",
  "prioritisation", "trade off", "opportunity cost", "diminishing returns",
  "economies of scale", "network effect", "lock in", "switching cost",
  "sunk cost", "moral hazard", "adverse selection", "free rider",
  "tragedy commons", "prisoners dilemma", "zero sum", "positive sum",
  "nash equilibrium", "game theory", "feedback loop", "runaway effect",
  "damping", "steady state", "equilibrium", "homeostasis", "resilience",
  "redundancy", "failover", "single point", "graceful degradation",
  "cascading failure", "chain reaction", "domino effect", "tipping point",
  "critical mass", "threshold", "inflection point", "step change",
  // observation and measurement
  "margin of error", "confidence interval", "significance", "sample bias",
  "selection bias", "survivorship bias", "confirmation bias",
  "anchoring", "framing", "base rate", "false positive", "false negative",
  "signal to noise", "outlier", "trend line", "regression", "correlation",
  "causation", "spurious link", "control group", "double blind",
  "placebo", "replication", "reproducibility", "peer review",
  "pre registration", "cherry picking", "data dredging", "overfitting",
  "underfitting", "extrapolation", "interpolation", "rounding error",
  "order of magnitude", "back of envelope", "rule of thumb",
  "ballpark", "sanity check", "sense check", "dry run", "pilot study",
  // states and transitions
  "warm up", "cool down", "ramp up", "wind down", "spin up", "shut down",
  "cold start", "hot swap", "hand over", "take over", "phase out",
  "roll out", "roll back", "fall back", "work around", "stop gap",
  "band aid", "patch", "hot fix", "quick fix", "permanent fix",
  "root cause", "symptom", "side effect", "knock on", "ripple effect",
  "unintended consequence", "law of unintended", "second order",
  "first order", "downstream", "upstream", "end to end", "edge case",
  "corner case", "happy path", "worst case", "best case", "average case",
];
