/**
 * HARD — you know exactly what it means, you just have no idea how to draw it.
 * One or two words, never a phrase.
 */
export const HARD: string[] = [
  // states of mind and body
  "deja vu", "nostalgia", "wanderlust", "homesickness", "stage fright",
  "cabin fever", "brain freeze", "brain fog", "food coma", "sugar rush",
  "jet lag", "insomnia", "hangover", "goosebumps", "shivers", "adrenaline",
  "willpower", "stamina", "exhaustion", "burnout", "second wind",
  "muscle memory", "autopilot", "tunnel vision", "blind spot", "reflex",
  "instinct", "intuition", "curiosity", "boredom", "impatience",
  "restlessness", "anticipation", "suspense", "relief", "regret",
  "gratitude", "envy", "jealousy", "pride", "guilt", "shame", "courage",
  "loyalty", "betrayal", "forgiveness", "grudge", "sarcasm", "irony",
  "awkwardness", "embarrassment", "confidence", "doubt", "panic", "calm",
  "serenity", "euphoria", "melancholy", "longing", "dread", "hope",
  "despair", "resilience", "stubbornness", "generosity", "greed",
  "kindness", "empathy", "patience", "temptation", "obsession",
  "addiction", "denial", "acceptance", "grief", "catharsis", "closure",
  // situations
  "small talk", "awkward silence", "cold shoulder", "silent treatment",
  "peer pressure", "culture shock", "writers block", "midlife crisis",
  "bad hair day", "wardrobe malfunction", "photobomb", "eye contact",
  "personal space", "third wheel", "inside joke", "dad joke", "punchline",
  "plot twist", "cliffhanger", "spoiler", "red herring", "plot hole",
  "false alarm", "close call", "near miss", "last minute", "overtime",
  "deadline", "crunch time", "rush hour", "traffic jam", "wrong turn",
  "dead end", "detour", "shortcut", "roadblock", "bottleneck", "gridlock",
  "queue jumping", "double booking", "no show", "rain check", "cold call",
  "cold feet", "buyers remorse", "impulse buy", "window shopping",
  "sticker shock", "price hike", "bargain hunting", "haggling",
  "split bill", "housewarming", "spring cleaning", "garage sale",
  "moving day", "power outage", "burst pipe", "leaky roof", "flat tire",
  "dead battery", "lost keys", "locked out", "missed flight", "layover",
  "lost luggage", "jetway", "turbulence", "seasickness", "sunburn",
  "paper cut", "stubbed toe", "pulled muscle", "static shock", "hiccups",
  // modern life
  "doom scrolling", "infinite scroll", "inbox zero", "spam folder",
  "autocorrect", "typo", "buffering", "low battery", "airplane mode",
  "dark mode", "incognito", "captcha", "two factor", "password reset",
  "screen time", "notification", "group chat", "voice memo", "voicemail",
  "read receipt", "reply all", "out of office", "screen share",
  "zoom call", "mute button", "bad connection", "dead zone", "roaming",
  "wifi password", "public wifi", "cracked screen", "storage full",
  "cloud backup", "software update", "blue screen", "force restart",
  "loading screen", "clickbait", "hot take", "echo chamber", "algorithm",
  "filter bubble", "targeted ad", "sponsored post", "influencer",
  "unboxing", "livestream", "podcast", "playlist", "shuffle mode",
  "skip ad", "binge watching", "next episode", "end credits", "reboot",
  "sequel", "prequel", "spin off", "fan theory", "meme", "viral video",
  "hashtag", "follower count", "unsubscribe", "ghosting", "left on read",
  "double text", "digital detox", "screen fatigue", "context switching",
  "multitasking", "flow state", "deep work", "busy work", "side hustle",
  "gig economy", "remote work", "hot desking", "open plan", "casual friday",
  // science and nature
  "gravity", "friction", "momentum", "inertia", "magnetism", "electricity",
  "static", "vacuum", "buoyancy", "density", "pressure", "evaporation",
  "condensation", "precipitation", "photosynthesis", "pollination",
  "germination", "food chain", "ecosystem", "habitat", "biodiversity",
  "extinction", "evolution", "camouflage", "mimicry", "hibernation",
  "migration", "metamorphosis", "regeneration", "symbiosis", "parasite",
  "nocturnal", "cold blooded", "metabolism", "digestion", "circulation",
  "heartbeat", "immune system", "vaccine", "antibiotic", "contagious",
  "quarantine", "pandemic", "allergy", "growth spurt", "rem sleep",
  "dreaming", "sleepwalking", "echo", "sonar", "radar", "sound wave",
  "prism", "refraction", "reflection", "optical illusion", "mirage",
  "eclipse", "moon phase", "orbit", "zero gravity", "black hole",
  "wormhole", "big bang", "supernova", "solar flare", "space junk",
  "asteroid belt", "light year", "time travel", "time loop",
  "chain reaction", "domino effect", "critical mass", "tipping point",
  "half life", "nuclear fusion", "carbon footprint", "greenhouse effect",
  "global warming", "rising tide", "deforestation", "erosion", "fault line",
  "continental drift", "permafrost", "monsoon", "jet stream", "trade winds",
  // weather and time
  "thunderstorm", "downpour", "drizzle", "hailstorm", "blizzard",
  "avalanche", "landslide", "mudslide", "wildfire", "drought", "flood",
  "tsunami", "hurricane", "tornado", "typhoon", "sandstorm", "dust storm",
  "heat wave", "cold snap", "first frost", "indian summer", "dry spell",
  "rainy season", "harvest time", "petrichor", "distant thunder",
  "storm cloud", "clear skies", "double rainbow", "sun shower",
  "northern lights", "meteor shower", "midnight sun", "polar night",
  "sunrise", "twilight", "golden hour", "witching hour", "eleventh hour",
  "leap year", "millennium", "decade", "generation", "lifetime",
  "nanosecond", "groundhog day", "monday", "friday feeling",
  // abstract-ish but drawable-adjacent
  "silence", "shadow", "reflection pool", "symmetry", "balance",
  "gravity well", "momentum shift", "spiral staircase", "infinity",
  "eternity", "chaos", "order", "harmony", "dissonance", "rhythm",
  "tempo", "crescendo", "improvisation", "jam session", "sound check",
  "perfect pitch", "tone deaf", "earworm", "tongue twister", "brainstorm",
  "comfort zone", "learning curve", "growing pains", "trial run",
  "dress rehearsal", "final draft", "rough sketch", "blank page",
  "fresh start", "clean slate", "full circle", "turning point",
  "crossroads", "leap of faith", "calculated risk", "gut feeling",
  "sixth sense", "premonition", "coincidence", "serendipity", "karma",
  "superstition", "jinx", "curse", "blessing", "lucky streak",
  "losing streak", "beginners luck", "long shot", "safe bet", "jackpot",
  "wild card", "dark horse", "underdog", "comeback", "victory lap",
  "sore loser", "poker face", "bluff", "stalemate", "checkmate",
  "sudden death", "photo finish", "dead heat", "false start",
  "home advantage", "away game", "hat trick", "own goal", "time out",
  "half time", "injury time", "sportsmanship", "fair play", "rivalry",
];
