/** HARD, part two — trades, systems, and things with moving parts. 1-2 words. */
export const HARD2: string[] = [
  // work and money
  "office politics", "water cooler", "team building", "ice breaker",
  "performance review", "job interview", "elevator pitch", "cover letter",
  "business card", "expense report", "petty cash", "payday", "paycheck",
  "direct deposit", "tax return", "tax season", "budget", "savings",
  "emergency fund", "compound interest", "inflation", "recession",
  "stock market", "bull market", "bear market", "market crash",
  "supply chain", "back order", "out of stock", "clearance sale",
  "black friday", "loyalty card", "cash back", "hidden fee",
  "free trial", "auto renewal", "small print", "sunk cost", "break even",
  "profit margin", "start up", "pitch deck", "angel investor",
  "hostile takeover", "merger", "downsizing", "promotion", "raise",
  "glass ceiling", "career ladder", "corporate ladder", "golden parachute",
  "exit interview", "notice period", "counter offer", "mentorship",
  "delegation", "micromanagement", "quiet quitting", "presenteeism",
  "workaholic", "vacation guilt", "work life", "commute",
  // medicine and the body
  "check up", "second opinion", "waiting room", "blood test", "flu shot",
  "booster", "prescription", "side effect", "dosage", "bedside manner",
  "house call", "night shift", "anesthesia", "stitches", "physical therapy",
  "recovery room", "heart monitor", "pulse check", "blood pressure",
  "eye test", "hearing test", "root canal", "wisdom tooth", "cavity",
  "flossing", "growth chart", "allergy test", "food intolerance",
  "gluten free", "dehydration", "heat stroke", "hypothermia", "frostbite",
  "altitude sickness", "motion sickness", "sleep apnea", "sleep debt",
  "power nap", "body clock", "circadian rhythm", "puberty", "grey hair",
  "bald spot", "wrinkle", "posture", "back pain", "text neck",
  "carpal tunnel", "eye strain", "blue light",
  // law and order
  "contract", "handshake deal", "fine print", "small claims",
  "power of attorney", "inheritance", "custody", "class action",
  "settlement", "gag order", "reasonable doubt", "forensics", "dna match",
  "lie detector", "interrogation", "confession", "cover up", "conspiracy",
  "whistleblower", "anonymous tip", "neighborhood watch", "crime scene",
  "police sketch", "wanted poster", "manhunt", "bounty hunter",
  "extradition", "asylum", "alibi", "eyewitness", "police lineup",
  "cold case", "smoking gun", "stakeout", "getaway car", "police chase",
  "handcuffs", "prison break", "parole", "community service",
  // building and making
  "blueprint", "floor plan", "foundation", "framing", "insulation",
  "drywall", "plastering", "sanding", "priming", "second coat", "grout",
  "caulk", "sealant", "plumb bob", "stud finder", "sawdust", "wood grain",
  "dovetail", "nail gun", "torque wrench", "socket set", "allen key",
  "hex bolt", "washer", "shim", "bearing", "bushing", "gasket",
  "grease fitting", "oil change", "spark plug", "timing belt",
  "radiator leak", "brake pad", "clutch", "transmission", "gear ratio",
  "suspension", "shock absorber", "wheel alignment", "tire tread",
  "air filter", "engine knock", "jump lead", "alternator", "starter motor",
  "assembly line", "conveyor belt", "robot arm", "laser cutter",
  "solar oven", "wind vane", "rain gauge", "barometer", "seismograph",
  "pendulum", "pulley", "lever", "gear train", "flywheel", "piston",
  "crankshaft", "camshaft", "turbine", "generator", "transformer",
  // craft and art
  "first draft", "thumbnail sketch", "life drawing", "still life",
  "self portrait", "abstract art", "brush stroke", "palette knife",
  "color theory", "vanishing point", "golden ratio", "negative space",
  "focal point", "composition", "underpainting", "glazing", "impasto",
  "watercolor", "ink wash", "charcoal", "pastel", "collage", "montage",
  "stencil", "screen print", "lino cut", "etching", "engraving",
  "calligraphy", "typography", "kerning", "serif", "hand lettering",
  "logo design", "mood board", "style guide", "wireframe", "mockup",
  "prototype", "iteration", "final proof", "print run", "gallery opening",
  "artist statement", "art forgery", "restoration", "conservation",
  // music and sound
  "key change", "time signature", "syncopation", "backbeat", "downbeat",
  "crescendo", "staccato", "legato", "vibrato", "tremolo", "reverb",
  "feedback", "amp buzz", "acoustic version", "cover version", "remix",
  "mashup", "sampling", "one hit", "b side", "deep cut", "hidden track",
  "album art", "liner notes", "gold record", "chart topper", "encore",
  "lip sync", "playback", "backing track", "session musician", "roadie",
  "sold out", "front row", "wall of sound", "shower singing",
  "wrong lyrics", "air guitar", "drum solo", "guitar solo", "crowd surfing",
  "mosh pit", "festival tent", "vinyl", "radio dj", "news anchor",
  "weather map", "live report", "press conference", "award show",
  "acceptance speech", "paparazzi", "autograph", "fan club",
  // food thinking
  "secret ingredient", "family recipe", "from scratch", "pinch of salt",
  "low and slow", "high heat", "mise en place", "prep station",
  "cross contamination", "food safety", "use by", "best before",
  "batch cooking", "meal prep", "cheat day", "portion size", "leftovers",
  "doggy bag", "takeout", "delivery", "tip jar", "grocery list",
  "impulse aisle", "bulk buy", "self checkout", "shrinkflation",
  "food envy", "menu regret", "sharing plates", "last slice",
  "double dipping", "clean plate", "picky eater", "hangry", "food fight",
  "messy eater", "spilled drink", "burnt dinner", "kitchen disaster",
];
