/** MEDIUM, part two — more staged scenes, objects with a twist, and moments. */
export const MEDIUM2: string[] = [
  // animals doing things
  "cat in a box", "dog chasing tail", "cat on a keyboard", "dog fetching",
  "puppy in a bag", "cat nap", "sleeping dog", "barking dog",
  "howling wolf", "roaring lion", "elephant spray", "monkey swinging",
  "bird in a nest", "hatching egg", "duck line", "flock of birds",
  "bird migration", "owl at night", "woodpecker knock", "peacock display",
  "swimming duck", "jumping fish", "leaping dolphin", "whale spout",
  "shark fin", "crab walk", "turtle race", "snail trail", "busy bee",
  "ant parade", "spider spinning", "butterfly emerging", "caterpillar munch",
  "frog on a lily pad", "croaking frog", "snake charmer", "sunbathing lizard",
  "hibernating bear", "squirrel burying nut", "beaver dam", "mole hill",
  "kangaroo pouch", "koala on eucalyptus", "sloth hanging", "camel caravan",
  "horse jumping", "galloping horse", "rodeo bull", "bucking bronco",
  "cow jumping moon", "sheep counting", "pig in mud", "rooster crowing",
  "hen sitting", "chicks following", "goat on a roof", "herd of cattle",
  "stampede", "safari jeep", "animal tracks", "paw print", "birds on a wire",
  "cat and mouse", "dog and postman", "trojan cat", "zoo enclosure",
  "animal shelter", "vet visit", "dog grooming", "cat scratching post",
  // gadgets and contraptions
  "rube goldberg", "mouse trap", "clothes line", "clothes peg",
  "laundry basket", "ironing board", "sewing kit", "pin cushion",
  "thimble", "measuring tape", "spirit level", "plumb line", "pulley",
  "lever", "gear train", "conveyor belt", "assembly line", "robot arm",
  "laser cutter", "solar oven", "wind vane", "rain gauge", "barometer",
  "seismograph", "sundial shadow", "water clock", "pendulum",
  "hamster wheel", "treadmill", "exercise bike", "rowing machine",
  "weight bench", "resistance band", "yoga mat", "foam roller",
  "skipping rope", "punch bag", "speed bag", "helmet cam",
  "bike pump", "bike lock", "bike bell", "training wheels",
  "car jack", "jumper cables", "spare tire", "roof rack", "trailer hitch",
  "snow chains", "windshield wiper", "rear view mirror", "dashboard",
  "seat belt", "car seat", "steering lock", "hood open", "engine smoke",
  // clothing and style
  "wardrobe malfunction", "mismatched socks", "hand me downs",
  "dress up box", "costume rack", "fitting room", "price tag on sleeve",
  "shopping spree", "window shopping", "sale rack", "clearance bin",
  "school uniform", "band uniform", "chef hat", "graduation cap",
  "tuxedo", "wedding dress", "veil", "flower crown", "corsage",
  "bow tie and suit", "top hat and cane", "raincoat and boots",
  "winter layers", "beach outfit", "safari hat", "hard hat",
  "lab coat", "scrubs", "dungarees", "apron and gloves", "hairnet",
  "face paint", "clown makeup", "stage makeup", "false mustache",
  "eye patch", "monocle", "pocket watch", "cufflinks", "shoe shine",
  // household and food moments
  "breakfast tray", "packed lunch", "school cafeteria", "office canteen",
  "vending snack run", "coffee break", "tea ceremony", "afternoon tea",
  "dinner party", "potluck", "barbecue grill", "grill smoke",
  "burnt sausage", "salad bowl toss", "cheese board", "fondue pot",
  "birthday singing", "candle blowing", "cake cutting", "party popper",
  "champagne pop", "toast speech", "food fight", "messy eater",
  "spilled drink", "napkin tuck", "ordering food", "restaurant menu",
  "waiter tray", "bill splitting", "tipping", "reservation",
  "table for two", "candlelit dinner", "picnic ants", "outdoor cafe",
  "street food cart", "night market", "farm stand", "roadside stall",
  // travel
  "packing a bag", "overweight luggage", "luggage carousel",
  "passport control", "boarding pass scan", "window seat", "aisle seat",
  "middle seat squeeze", "tray table", "seat belt sign", "airplane meal",
  "turbulence", "takeoff", "landing", "jet bridge", "airport lounge",
  "duty free", "souvenir shop", "postcard rack", "tourist map",
  "selfie at landmark", "tour bus", "guided tour", "hotel check in",
  "room service", "do not disturb sign", "hotel pool", "beach towel",
  "sunbathing", "sunburn", "sunscreen", "beach ball game", "sandcastle moat",
  "seashell collecting", "boardwalk", "pier arcade", "ferry crossing",
  "road trip", "car games", "backseat argument", "rest stop",
  "scenic overlook", "motel sign", "camper van", "caravan", "roof tent",
  "train sleeper", "night bus", "hitchhiking", "backpacking",
  "hostel bunk", "border crossing", "currency exchange", "lost luggage",
  // school and work
  "homework", "pop quiz", "final exam", "report card", "gold star",
  "teachers desk", "chalk dust", "raising hand", "class photo",
  "field trip", "school assembly", "detention", "recess", "lunch line",
  "locker", "yearbook", "prom", "school dance", "cap toss",
  "lecture hall", "study group", "all nighter", "library silence",
  "flash cards", "science experiment", "volcano project", "solar model",
  "dissection", "microscope slide", "periodic table", "chalkboard math",
  "long division", "geometry set", "protractor", "compass drawing",
  "office cubicle", "water cooler chat", "coffee machine queue",
  "meeting room", "whiteboard brainstorm", "sticky note wall",
  "conference call", "presentation slide", "laser pointer",
  "handshake deal", "business card", "briefcase", "filing cabinet",
  "paper stack", "inbox tray", "out of office", "desk plant",
  "swivel chair", "standing desk", "keyboard clatter", "printer queue",
  "office party", "secret santa", "team photo", "employee of month",
  "punch clock", "name badge", "id lanyard", "elevator ride",
  // city life
  "rush hour", "traffic jam", "honking horn", "jaywalking",
  "crossing guard", "street performer", "busker", "human statue",
  "chalk artist", "food delivery bike", "bike courier", "newspaper stand",
  "shoe shiner", "hot dog cart", "pretzel cart", "street sweeper",
  "garbage day", "recycling bins", "graffiti wall", "mural painting",
  "billboard", "neon street", "subway map", "turnstile", "escalator rush",
  "packed train", "standing room", "missed stop", "platform gap",
  "taxi hail", "ride share pickup", "double parking", "parking ticket",
  "tow truck removal", "meter maid", "speed bump", "pothole",
  "roadworks", "detour route", "one way street", "dead end sign",
  "street lamp glow", "fire escape", "rooftop garden", "window box",
  "laundry line", "apartment balcony", "doorman", "buzzer",
  "elevator music", "stairwell", "mailboxes", "package delivery",
  "porch pirate", "welcome mat", "garden gnome", "picket fence",
  "sprinkler run", "car wash bucket", "driveway hoop", "block party grill",
  // seasons and holidays
  "spring blossom", "summer heat", "autumn leaves", "winter frost",
  "first snow", "snowball fight", "snow shovel", "icicle drip",
  "sledding hill", "skating pond", "hot cocoa", "fireplace stockings",
  "christmas tree", "tree decorating", "tinsel", "gift wrapping",
  "carol singing", "advent calendar", "new year countdown",
  "fireworks midnight", "resolution list", "valentine card",
  "heart balloon", "love letter", "cupid arrow", "spring cleaning day",
  "easter basket", "egg painting", "may pole", "summer camp",
  "camp bunk", "canoe trip", "fourth of july", "beach barbecue",
  "harvest festival", "corn maze", "hay ride", "pumpkin patch",
  "pumpkin carving", "costume parade", "candy bucket", "thanksgiving turkey",
  "family dinner", "wishbone pull", "black friday", "holiday traffic",
  "airport at holidays", "diwali lamps", "lantern festival",
  "dragon dance", "fireworks festival", "carnival float", "mardi gras beads",
  "pinata swing", "birthday banner", "anniversary dinner", "baby announcement",
  // stage and screen
  "movie premiere", "red carpet", "popcorn bucket", "cinema glasses",
  "front row seat", "silent film", "clapper board", "boom mic",
  "green screen", "stunt fall", "explosion scene", "car chase",
  "slow motion replay", "director chair", "film reel", "movie poster",
  "ticket stub", "usher flashlight", "credits rolling", "sequel teaser",
  "stage curtain", "spotlight solo", "orchestra warm up", "backstage pass",
  "dressing room", "understudy", "standing ovation", "encore call",
  "puppet strings", "marionette", "ventriloquist", "stand up comic",
  "open mic", "karaoke", "battle of bands", "guitar solo", "drum solo",
  "crowd surfing", "mosh pit", "concert lighter", "festival tent",
  "vinyl crate digging", "radio dj", "podcast mic", "news anchor",
  "weather map", "live report", "camera crew", "press conference",
  "award show", "acceptance speech", "golden statue", "paparazzi",
  "autograph hunt", "fan club", "movie marathon", "binge watching",
];
