/**
 * MEDIUM — still drawable, but you have to think about how. Scenes, actions,
 * compound objects, roles, and things that need a bit of staging.
 */
export const MEDIUM: string[] = [
  // scenes you have to stage
  "treasure chest", "campfire", "picnic blanket", "beach umbrella",
  "sand castle", "snow fort", "blanket fort", "lemonade stand",
  "garage sale", "yard sale sign", "farmers market", "flea market",
  "food truck", "ice cream truck", "hot dog stand", "coffee shop",
  "bakery window", "butcher shop", "barber shop", "beauty salon",
  "bowling alley", "movie theater", "drive in movie", "arcade",
  "amusement park", "ferris wheel", "roller coaster", "carousel",
  "bumper cars", "haunted house", "fun house mirror", "ticket booth",
  "petting zoo", "aquarium tank", "planetarium", "observatory",
  "art gallery", "museum exhibit", "public library", "book club",
  "classroom", "school play", "science fair", "spelling bee",
  "graduation ceremony", "wedding ceremony", "wedding cake",
  "birthday party", "baby shower", "surprise party", "family reunion",
  "block party", "street parade", "marching band", "fireworks show",
  "concert stage", "rock concert", "orchestra pit", "talent show",
  "magic show", "circus tent", "trapeze act", "tightrope walk",
  "lion tamer", "clown car", "juggling act", "puppet show",
  "shadow puppet", "sock puppet", "campsite", "camp fire ring",
  "sleeping bag", "hiking trail", "mountain summit", "rope bridge",
  "log cabin", "fishing hole", "duck pond", "bird watching",
  "star gazing", "night sky", "meteor shower", "northern lights",
  "sunset beach", "tide pool", "coral reef", "shipwreck",
  "message in a bottle", "desert island", "buried treasure",
  "treasure map", "pirate ship", "walking the plank", "crows nest",
  "castle moat", "drawbridge", "watchtower", "dungeon", "throne room",
  "royal banquet", "knight in armor", "jousting", "sword fight",
  "archery range", "catapult", "battering ram", "siege tower",
  // places and landmarks
  "skyscraper", "city skyline", "suburb", "farmhouse", "silo",
  "grain elevator", "water tower", "windmill farm", "solar panel",
  "wind turbine", "oil rig", "power plant", "factory", "warehouse",
  "construction site", "scaffolding", "wrecking ball", "crane lift",
  "road work", "detour sign", "toll booth", "gas station", "car wash",
  "parking garage", "parking lot", "bus stop", "bus shelter",
  "train station", "train platform", "subway entrance", "airport terminal",
  "airport runway", "control tower", "baggage claim", "boarding gate",
  "harbor", "dock", "pier", "marina", "lighthouse cliff", "canal lock",
  "dam", "reservoir", "aqueduct", "suspension bridge", "covered bridge",
  "tunnel entrance", "roundabout", "overpass", "highway exit",
  "post office", "fire station", "police station", "city hall",
  "courthouse", "hospital ward", "emergency room", "dentist chair",
  "waiting room", "pharmacy", "grocery store", "supermarket aisle",
  "checkout line", "shopping mall", "food court", "elevator doors",
  "escalator", "revolving door", "vending machine", "laundromat",
  "hotel lobby", "hotel room", "swimming pool", "diving board",
  "water slide", "hot tub", "sauna", "gym", "locker room", "stadium",
  "race track", "finish line tape", "podium", "scoreboard lights",
  "pyramid", "sphinx", "colosseum", "great wall", "eiffel tower",
  "statue of liberty", "leaning tower", "taj mahal", "big ben",
  "stonehenge", "totem pole", "obelisk", "temple", "pagoda", "mosque",
  "cathedral", "chapel", "bell tower", "monastery", "shrine",
  // jobs
  "police officer", "firefighter", "paramedic", "surgeon", "nurse shift",
  "veterinarian", "dentist", "optician", "pharmacist", "scientist",
  "chemist", "biologist", "archaeologist", "astronomer", "geologist",
  "engineer", "architect", "electrician", "plumber", "carpenter",
  "bricklayer", "welder", "painter", "roofer", "landscaper", "gardener",
  "farmer", "rancher", "shepherd", "fisherman", "lumberjack", "miner",
  "blacksmith", "potter", "weaver", "tailor", "cobbler", "watchmaker",
  "jeweler", "baker", "butcher", "chef", "sous chef", "barista",
  "bartender", "waiter", "cashier", "shopkeeper", "librarian", "teacher",
  "professor", "principal", "coach", "referee", "umpire", "lifeguard",
  "pilot", "flight attendant", "sailor", "captain", "train conductor",
  "bus driver", "taxi driver", "truck driver", "delivery driver",
  "mail carrier", "garbage collector", "janitor", "security guard",
  "detective", "lawyer", "judge", "accountant", "banker", "realtor",
  "journalist", "photographer", "film director", "camera operator",
  "actor", "actress", "stunt double", "magician", "juggler", "acrobat",
  "ballerina", "opera singer", "dj", "drummer", "conductor",
  "sculptor", "cartoonist", "tattoo artist", "hairdresser", "masseuse",
  "personal trainer", "yoga teacher", "babysitter", "tour guide",
  "park ranger", "zookeeper", "dog walker", "beekeeper", "florist",
  // actions
  "sneezing", "yawning", "hiccups", "coughing", "snoring", "sleepwalking",
  "daydreaming", "nightmare", "oversleeping", "hitting snooze",
  "brushing teeth", "washing hands", "taking a shower", "shaving",
  "getting a haircut", "tying shoelaces", "buttoning a shirt",
  "packing a suitcase", "unpacking", "making the bed", "folding laundry",
  "ironing", "doing dishes", "sweeping", "mopping", "vacuuming",
  "taking out trash", "walking the dog", "feeding the cat",
  "watering plants", "mowing the lawn", "raking leaves", "shoveling snow",
  "washing the car", "changing a tire", "pumping gas", "parallel parking",
  "backing up", "hailing a taxi", "missing the bus", "running late",
  "checking the time", "setting an alarm", "answering the phone",
  "texting", "taking a selfie", "video call", "scrolling",
  "reading a book", "turning a page", "writing a letter",
  "licking a stamp", "opening mail", "wrapping a gift", "blowing candles",
  "cutting cake", "toasting glasses", "clinking mugs", "pouring tea",
  "spilling coffee", "burning toast", "flipping pancakes", "stirring pot",
  "chopping onions", "kneading dough", "rolling dough", "grating cheese",
  "peeling a banana", "cracking an egg", "squeezing a lemon",
  "eating spaghetti", "slurping noodles", "biting a burger",
  "sharing dessert", "licking an ice cream", "blowing bubbles",
  "chewing gum", "popping a balloon", "blowing up a balloon",
  "flying a kite", "skipping stones", "climbing a tree", "swinging",
  "sliding down", "jumping rope", "hopscotch", "leapfrog", "piggyback",
  "cartwheel", "somersault", "handstand", "headstand", "backflip",
  "tightrope", "juggling", "spinning plates", "hula hooping",
  "riding a bike", "falling off", "skinned knee", "getting a bandage",
  "high five", "fist bump", "handshake", "hugging", "waving goodbye",
  "blowing a kiss", "pointing", "shrugging", "clapping", "thumbs up",
  "crossing fingers", "covering ears", "peeking", "tiptoeing",
  "sneaking", "hiding", "seeking", "chasing", "tripping", "slipping",
  "faceplant", "bumping heads", "stubbing a toe", "catching a ball",
  "dropping a ball", "kicking a ball", "throwing a snowball",
  "building a snowman", "making snow angels", "sledding", "ice skating",
  "roller skating", "skateboarding", "surfing a wave", "wiping out",
  "swimming laps", "cannonball dive", "belly flop", "floating",
  "treading water", "snorkeling", "scuba diving", "deep sea diving",
  "rowing", "paddling", "sailing", "anchoring", "casting a line",
  "reeling in", "catching a fish", "throwing it back", "pitching a tent",
  "roasting marshmallows", "telling ghost stories", "singing campfire song",
  "hiking uphill", "reading a map", "using a compass", "getting lost",
  "climbing a rope", "rappelling", "rock climbing", "bouldering",
  "zip lining", "bungee jumping", "skydiving", "hang gliding",
  "hot air ballooning", "parasailing", "riding a horse", "milking a cow",
  "shearing a sheep", "collecting eggs", "planting seeds", "harvesting",
  "picking apples", "scaring crows", "bailing hay", "herding sheep",
  // sports
  "penalty kick", "corner kick", "header goal", "goal celebration",
  "red card", "slam dunk", "three pointer", "free throw", "layup",
  "home run", "strike out", "stealing a base", "catching a fly ball",
  "touchdown", "field goal", "tackle", "huddle", "quarterback throw",
  "tennis serve", "backhand", "match point", "badminton smash",
  "table tennis rally", "golf swing", "hole in one", "putting green",
  "sand trap", "hockey face off", "slap shot", "goalie save",
  "boxing match", "knockout punch", "wrestling pin", "judo throw",
  "karate chop", "black belt", "fencing duel", "archery bullseye",
  "marathon runner", "relay race", "baton pass", "hurdle jump",
  "long jump", "high jump", "pole vaulting", "shot put throw",
  "javelin throw", "discus throw", "gymnastics beam", "uneven bars",
  "vault landing", "figure skating", "speed skating", "ski jump",
  "slalom", "snowboard trick", "bobsled", "curling", "luge",
  "cycling race", "mountain biking", "bmx trick", "motocross",
  "formula one", "pit stop", "checkered flag finish", "podium finish",
  "rowing crew", "kayak rapids", "white water rafting", "sumo wrestling",
  "cheerleading pyramid", "half time show", "mascot", "stadium wave",
  "sports commentary", "instant replay", "team huddle", "coin toss",
  // food of the world
  "sushi roll", "sashimi", "ramen bowl", "miso soup", "tempura",
  "dumpling", "spring roll", "fried rice", "noodle stir fry",
  "peking duck", "dim sum", "bao bun", "pad thai", "green curry",
  "pho bowl", "banh mi", "satay skewer", "nasi goreng", "biryani",
  "butter chicken", "samosa", "naan bread", "tandoori chicken",
  "masala dosa", "idli", "chai tea", "falafel", "hummus", "shawarma",
  "kebab skewer", "gyro", "baklava", "couscous", "tagine", "paella",
  "tapas", "churros", "empanada", "quesadilla", "enchilada", "tamale",
  "guacamole", "salsa bowl", "ceviche", "feijoada", "poutine",
  "shepherds pie", "fish and chips", "bangers and mash", "full breakfast",
  "scone", "crumpet", "yorkshire pudding", "pretzel stand", "bratwurst",
  "schnitzel", "sauerkraut", "goulash", "borscht", "pierogi",
  "swedish meatballs", "smorgasbord", "pizza margherita", "lasagna",
  "risotto", "gnocchi", "ravioli", "carbonara", "tiramisu", "gelato",
  "cannoli", "espresso shot", "cappuccino art", "croissant breakfast",
  "baguette sandwich", "quiche", "ratatouille", "creme brulee",
  "macaron", "eclair", "souffle", "waffle stack", "banana split",
  "root beer float", "milkshake diner", "apple pie", "pumpkin pie",
  "cheesecake", "carrot cake", "red velvet cake", "layer cake",
  "wedding cake tier", "birthday cake candles", "gingerbread house",
  "candy apple", "caramel corn", "funnel cake", "corn dog",
  "cotton candy stand", "shaved ice", "smoothie bowl", "bubble tea",
  "trail mix", "granola", "avocado toast", "eggs benedict",
  "breakfast in bed", "brunch spread", "buffet line", "leftovers",
  "doggy bag", "takeout box", "delivery bag", "tip jar",
  // weather and nature events
  "thunderstorm", "lightning strike", "rainbow after rain", "downpour",
  "drizzle", "hailstorm", "blizzard", "snowdrift", "avalanche",
  "ice storm", "frost pattern", "morning dew", "heat wave", "mirage",
  "dust storm", "sandstorm", "tornado", "hurricane", "typhoon",
  "flood", "flash flood", "drought", "wildfire", "smoke plume",
  "earthquake crack", "landslide", "mudslide", "volcanic eruption",
  "lava flow", "ash cloud", "tsunami", "tidal wave", "riptide",
  "waterspout", "whirlwind", "eye of the storm", "storm cloud",
  "clear skies", "moonlit night", "solar eclipse", "lunar eclipse",
  "double rainbow", "sun shower", "fog bank", "sea breeze",
  // gadgets and machines
  "washing machine", "clothes dryer", "sewing machine", "knitting needles",
  "spinning wheel", "loom", "printing press", "typewriter keys",
  "film projector", "slide projector", "jukebox", "gramophone",
  "record player", "cassette player", "walkman", "boom box",
  "video game console", "arcade cabinet", "pinball machine",
  "claw machine", "photo booth", "polaroid camera", "camera flash",
  "tripod", "drone", "remote control car", "walkie talkies",
  "metal detector", "lie detector", "cash machine", "parking ticket",
  "traffic camera", "speed radar", "megaphone", "loudspeaker",
  "microphone stand", "mixing desk", "guitar amp", "disco ball",
  "strobe light", "lava lamp", "neon sign", "marquee lights",
  "ceiling projector", "smart speaker", "robot vacuum", "electric fan",
  "space heater", "air conditioner", "humidifier", "water cooler",
  "coffee grinder", "espresso machine", "popcorn machine",
  "cotton candy machine", "slot machine", "gumball machine",
  "vending snack", "photocopier", "shredder", "fax machine",
  "landline phone", "rotary phone", "phone booth", "pay phone",
  "telegraph", "morse code", "semaphore flags", "lighthouse beam",
  "periscope", "submarine hatch", "diving bell", "space capsule",
  "moon lander", "mars rover", "space suit", "jet pack", "hoverboard",
  "time machine", "teleporter", "ray gun", "force field",
  // myth and story
  "unicorn horn", "pegasus", "griffin", "phoenix", "centaur", "minotaur",
  "cyclops", "medusa", "kraken", "loch ness monster", "bigfoot", "yeti",
  "werewolf", "vampire bat", "haunted mirror", "crystal ball",
  "magic wand", "spell book", "cauldron", "potion bottle", "witch hat",
  "broomstick", "flying carpet", "magic lamp", "genie", "wishing star",
  "fairy godmother", "glass slipper", "poisoned apple", "beanstalk",
  "golden goose", "gingerbread man", "big bad wolf", "three bears",
  "tortoise and hare", "trojan horse", "excalibur", "holy grail",
  "philosophers stone", "pot of gold", "leprechaun", "tooth fairy",
  "santa sleigh", "reindeer team", "elf workshop", "stocking",
  "easter bunny", "easter egg hunt", "jack o lantern", "trick or treat",
  "costume party", "haunted mansion", "black cat", "full moon howl",
  "grim reaper", "guardian angel", "devil and angel", "genie lamp rub",
  // household moments
  "moving day", "cardboard boxes", "bubble wrap", "packing tape",
  "housewarming", "spring cleaning", "closet chaos", "junk drawer",
  "laundry pile", "dish pile", "leaky faucet", "clogged drain",
  "burnt dinner", "smoke alarm beeping", "power outage", "candle light",
  "blown fuse", "broken window", "squeaky door", "stuck drawer",
  "wobbly table", "flat tire", "dead battery", "jump start",
  "locked out", "spare key", "lost keys", "lost sock", "misplaced glasses",
  "remote hunt", "tangled cables", "knotted headphones", "low battery",
  "slow wifi", "buffering wheel", "printer jam", "spilled milk",
  "broken glass", "sweeping up", "band aid fix", "duct tape repair",
  "assembly instructions", "missing screw", "extra parts", "flat pack",
  "hanging a picture", "painting a wall", "wallpapering", "tiling",
  "changing a bulb", "smoke detector battery", "gutter cleaning",
  "weeding", "pruning", "composting", "bird feeding", "squirrel raid",
];
