/**
 * MEDIUM3 — the words that used to sit in the easy bank and outgrew it.
 *
 * When the easy tier became KIDS (see easy.ts), everything a five year old
 * would not say out loud — persimmon, brussels sprout, the woodwind half of
 * the orchestra — moved here rather than being thrown away. They are still
 * good pictionary words; they are just not kids' words. Nothing here is new.
 */
export const MEDIUM3: string[] = [
  "papaya", "cantaloupe", "apricot", "fig", "date", "pomegranate",
  "cranberry", "gooseberry", "lychee", "guava", "passion fruit",
  "starfruit", "dragon fruit", "jackfruit", "durian", "persimmon",
  "tangerine", "grapefruit", "clementine", "nectarine", "banana bunch",
  "fruit basket", "sweet potato", "ginger", "spinach", "kale", "zucchini",
  "squash", "eggplant", "beetroot", "radish", "turnip", "parsnip", "leek",
  "asparagus", "artichoke", "brussels sprout", "okra", "olive", "lentils",
  "chickpea", "soybean", "walnut", "almond", "cashew", "pistachio",
  "hazelnut", "chestnut", "pecan", "sunflower seed", "pumpkin seed",
  "rice", "wheat", "oats", "popcorn kernel", "bread loaf", "biscuit",
  "brownie", "tart", "crepe", "sundae", "gum", "caramel", "jam",
  "peanut butter", "cheese slice", "boiled egg", "omelette", "drumstick",
  "fish stick", "macaroni", "stew", "sandwich bag", "cereal bowl",
  "porridge", "pudding", "jelly", "yogurt", "chips", "nachos", "cracker",
  "granola bar", "pancake stack", "milk bottle", "coffee cup", "smoothie",
  "parakeet", "canary", "mule", "ox", "gosling", "sheepdog",
  "puppy basket", "cat bed", "litter box", "jaguar", "panther",
  "grizzly bear", "coyote", "jackal", "hyena", "bison", "elk", "fawn",
  "antelope", "gazelle", "wallaby", "orangutan", "baboon", "lemur",
  "badger", "weasel", "ferret", "wombat", "platypus", "opossum",
  "mongoose", "warthog", "yak", "falcon", "vulture", "raven", "sparrow",
  "bluebird", "cardinal", "canary bird", "macaw", "cockatoo", "crane bird",
  "heron", "puffin", "emu", "swallow", "magpie", "kingfisher",
  "nightingale", "quail", "pheasant", "partridge", "prawn", "oyster",
  "mussel", "scallop", "snail shell", "conch", "sea urchin", "sand dollar",
  "anemone", "manta ray", "angelfish", "catfish", "salmon", "tuna",
  "sardine", "trout", "carp", "manatee", "turtle shell", "hornet",
  "termite", "locust", "housefly", "flea", "tick", "earthworm",
  "millipede", "cicada", "aphid", "maggot", "larva", "viper", "boa",
  "newt", "thunder cloud", "hail", "fog", "wind", "tornado funnel", "sky",
  "meteor", "mars", "jupiter", "moon crater", "satellite", "space station",
  "astronaut helmet", "constellation", "solar system", "galaxy", "eclipse",
  "aurora", "willow", "orchid", "poppy", "lavender", "root", "sapling",
  "moss", "fern", "vine", "valley", "canyon", "swamp", "meadow", "field",
  "orchard", "stream", "whirlpool", "glacier", "boulder", "dirt pile",
  "snow drift", "sinkhole", "mansion", "apartment", "porch", "balcony",
  "front door", "shutter", "blind", "staircase", "attic", "basement",
  "floor lamp", "coffee table", "dresser", "wardrobe", "closet", "cabinet",
  "cupboard", "carpet", "cushion", "quilt", "mattress", "wall clock",
  "candlestick", "night light", "flower pot", "freezer", "coffee maker",
  "mixer", "dishwasher", "ladle", "tongs", "grater", "peeler", "corkscrew",
  "measuring cup", "mixing bowl", "saucepan", "pot lid", "wok",
  "baking tray", "cake tin", "colander", "strainer", "teaspoon", "saucer",
  "wine glass", "pitcher", "pepper mill", "sugar bowl", "tablecloth",
  "recycling bin", "dish soap", "dish rack", "shower head", "soap bar",
  "razor", "scale", "bath mat", "cotton swab", "mouthwash", "blouse",
  "vest", "suit", "shawl", "gown", "robe", "swim trunks", "stockings",
  "tights", "loafer", "cleats", "beanie", "sun hat", "suspenders",
  "pocket", "purse", "duffel bag", "brooch", "top", "checkers",
  "kaleidoscope", "bass guitar", "cello", "keyboard", "organ",
  "triangle bell", "french horn", "clarinet", "oboe", "metronome",
  "record", "cassette", "boombox", "handsaw", "hatchet", "chisel", "file",
  "sandpaper", "bolt", "nut", "washer", "level", "carpenter square",
  "clamp", "vise", "workbench", "spade", "hoe", "hedge trimmer", "wire",
  "cable", "nail gun", "extension cord", "nail file", "shears", "textbook",
  "diary", "journal", "binder", "staple", "pushpin", "backpack strap",
  "scanner", "video camera", "usb stick", "hard drive", "router",
  "minivan", "trolley", "tram", "subway train", "monorail", "train car",
  "caboose", "moped", "cart", "wheelbarrow cart", "cargo ship", "yacht",
  "gondola", "glider", "hovercraft", "engine", "road sign", "highway",
  "sidewalk", "parking meter", "manhole cover", "ogre", "snowman face",
  "eyelash", "forehead", "sideburns", "wrist", "palm", "fingernail",
  "ankle", "heel", "lungs", "ribcage", "spine", "back", "kettlebell",
  "jump ball", "ribbon award", "starting block", "javelin", "discus",
  "shot put", "pole vault", "tackle box", "skate ramp", "helmet pads",
  "crown symbol", "lightbulb idea", "musical note", "recycle symbol",
  "yin yang", "infinity", "hashtag", "at sign", "percent sign",
  "cake candle", "invitation", "banknote", "gold bar", "diamond ring",
  "crown jewels", "trophy cup", "medal ribbon", "telescope small", "flask",
  "magnet horseshoe", "thermometer outdoor", "barometer", "weather vane",
  "sundial", "beehive box", "scarecrow hat", "water tower", "smoke alarm",
  "siren", "traffic camera", "security camera", "atm machine", "barcode",
  "receipt", "gift card",
];
