/**
 * ULTRA — the deep end. Pure abstractions with no obvious picture at all,
 * but every one is a word people actually say, so the room can shout it out
 * the moment the drawing finally clicks. One or two words, never a phrase.
 */
export const ULTRA: string[] = [
  // big ideas
  "freedom", "justice", "equality", "liberty", "democracy", "anarchy",
  "utopia", "dystopia", "capitalism", "socialism", "globalization",
  "colonialism", "independence", "sovereignty", "patriotism",
  "nationalism", "diplomacy", "bureaucracy", "corruption", "nepotism",
  "meritocracy", "propaganda", "censorship", "free speech", "human rights",
  "civil disobedience", "revolution", "reform", "protest", "boycott",
  "referendum", "election", "landslide", "term limit", "filibuster",
  "red tape", "power vacuum", "checks and balances", "rule of law",
  "accountability", "transparency", "social contract", "public good",
  "greater good", "lesser evil", "moral dilemma", "double standard",
  "hypocrisy", "integrity", "principle", "compromise", "consensus",
  "solidarity", "class divide", "wealth gap", "poverty line",
  "safety net", "social mobility", "gentrification", "urban sprawl",
  // mind and philosophy
  "consciousness", "self awareness", "identity", "ego", "subconscious",
  "free will", "determinism", "fate", "destiny", "purpose", "ambition",
  "motivation", "discipline", "self control", "instant gratification",
  "opportunity cost", "trade off", "diminishing returns", "paradox",
  "contradiction", "catch twenty two", "vicious circle", "feedback loop",
  "downward spiral", "rock bottom", "point of no return", "slippery slope",
  "moral compass", "conscience", "authenticity", "vulnerability",
  "resilience", "growth mindset", "imposter syndrome", "analysis paralysis",
  "decision fatigue", "confirmation bias", "hindsight bias",
  "survivorship bias", "groupthink", "herd mentality", "social proof",
  "bystander effect", "learned helplessness", "placebo effect",
  "butterfly effect", "chaos theory", "critical thinking",
  "scientific method", "thought experiment", "first principles",
  "mental model", "analogy", "metaphor", "hyperbole", "understatement",
  "euphemism", "wordplay", "anagram", "palindrome", "acronym",
  "double meaning", "freudian slip", "body language", "first impression",
  "second opinion", "benefit of doubt", "burden of proof", "grey area",
  "middle ground", "common ground", "nuance", "generalization",
  "assumption", "hidden agenda", "open secret", "white lie", "half truth",
  "rumor mill", "grapevine", "word of mouth", "peer review",
  // relationships
  "unconditional love", "tough love", "puppy love", "unrequited love",
  "long distance", "slow burn", "honeymoon phase", "growing apart",
  "reconciliation", "closure", "moving on", "old flame", "blind date",
  "first date", "popping the question", "shotgun wedding", "in laws",
  "sibling rivalry", "middle child", "only child", "empty nest",
  "helicopter parent", "family secret", "black sheep", "chosen family",
  "found family", "fair weather", "frenemy", "friendship breakup",
  "small world", "networking", "name dropping", "office crush",
  "boundaries", "personal bubble", "oversharing", "trust issues",
  "codependency", "passive aggression", "backhanded compliment",
  "faint praise", "sugar coating", "brutal honesty", "hard truth",
  "reality check", "wake up call", "rude awakening", "cold hard facts",
  // emotions with no shape
  "bittersweet", "mixed emotions", "emotional whiplash", "numbness",
  "overwhelm", "anticlimax", "letdown", "disillusionment",
  "disappointment", "resignation", "bargaining", "healing", "recovery",
  "compassion fatigue", "second hand stress", "anxiety spiral",
  "worry loop", "intrusive thought", "rumination", "self doubt",
  "inner critic", "inner child", "self sabotage", "self care",
  "people pleasing", "conflict avoidance", "de escalation", "mediation",
  "negotiation", "arbitration", "peacemaker", "instigator",
  "voice of reason", "devils advocate", "silent majority",
  "vocal minority", "tie breaker", "casting vote", "abstention",
  // time and change
  "the present", "living in the past", "future proofing", "long game",
  "short term", "delayed gratification", "slow living", "hustle culture",
  "career pivot", "gap year", "sabbatical", "early retirement",
  "bucket list", "unfinished business", "loose ends", "fresh chapter",
  "final chapter", "circle of life", "generation gap", "end of era",
  "new beginning", "history repeating", "same old story",
  "creature of habit", "change of scenery", "reverse culture shock",
  "adjustment period", "steep learning", "trial by fire", "baptism",
  "sink or swim", "deep end", "out of depth", "over your head",
  // systems and abstractions
  "information overload", "scope creep", "feature creep", "moving target",
  "shifting priorities", "fire fighting", "band aid", "technical debt",
  "reinventing the wheel", "premature optimization", "over engineering",
  "good enough", "murphys law", "peter principle", "pareto principle",
  "network effect", "first mover", "race to bottom", "arms race",
  "prisoners dilemma", "zero sum", "positive sum", "moral hazard",
  "perverse incentive", "free rider", "attention economy",
  "digital footprint", "online persona", "curated life", "highlight reel",
  "comparison trap", "fear of missing", "joy of missing",
  "notification fatigue", "productivity theatre", "single source",
  "chain of custody", "plausible deniability", "reading the room",
  "vibe check", "single point", "contingency plan", "worst case",
  "best case", "risk register", "post mortem", "root cause",
  "blame culture", "psychological safety", "constructive criticism",
  // scale and measure
  "microscopic", "macroscopic", "atomic", "subatomic", "quantum leap",
  "molecular", "cellular", "planetary", "galactic", "cosmic",
  "geological time", "human lifespan", "blink of eye", "overnight success",
  "compound growth", "exponential curve", "hockey stick", "plateau",
  "long tail", "bell curve", "outlier", "average", "median",
  "statistical anomaly", "margin of error", "confidence interval",
  "rounding error", "order of magnitude", "back of envelope",
  "ballpark estimate", "educated guess", "rough approximation",
  "probability", "randomness", "symmetry", "asymmetry", "proportion",
  "magnitude", "threshold", "boundary", "constraint", "potential",
  "kinetic", "latent", "dormant", "emergent", "inevitable", "impossible",
  "improbable", "hypothetical", "theoretical", "tangible", "intangible",
  "entropy", "equilibrium", "resonance", "complexity", "simplicity",
  "elegance", "efficiency", "redundancy", "fragility", "robustness",
  "adaptation", "optimization", "recursion", "infinite regress",
  "emergence", "mortality", "legacy", "reputation", "dignity", "honor",
  "duty", "sacrifice", "heroism", "conviction", "faith", "hope",
  "redemption", "atonement", "belonging", "outsider", "misfit",
  "collective memory", "shared history", "cultural identity", "roots",
  "displacement", "diaspora", "homeland", "exile", "refuge",
  "melting pot", "assimilation", "integration", "tolerance", "inclusion",
  "diversity", "stereotype", "prejudice", "discrimination", "bias",
];
