/** ULTRA, part three. Pure abstractions, one or two words. */
export const ULTRA3: string[] = [
  // virtues and vices
  "humility", "arrogance", "modesty", "vanity", "conceit", "hubris",
  "temperance", "gluttony", "prudence", "recklessness", "fortitude",
  "cowardice", "charity", "avarice", "diligence", "sloth", "chastity",
  "patience", "wrath", "serenity", "equanimity", "composure",
  "poise", "grace", "dignity", "decorum", "propriety", "impropriety",
  "candour", "discretion", "tact", "bluntness", "diplomacy", "guile",
  "cunning", "naivety", "innocence", "worldliness", "wisdom", "folly",
  "sagacity", "ignorance", "enlightenment", "delusion", "clarity",
  "confusion", "conviction", "vacillation", "resolve", "irresolution",
  // states of being
  "solitude", "loneliness", "isolation", "seclusion", "privacy",
  "exposure", "visibility", "obscurity", "anonymity", "notoriety",
  "fame", "infamy", "celebrity", "obsolescence", "relevance",
  "irrelevance", "prominence", "insignificance", "consequence",
  "inconsequence", "permanence", "impermanence", "transience",
  "ephemera", "continuity", "discontinuity", "stability", "volatility",
  "fragility", "durability", "endurance", "persistence", "abandonment",
  "commitment", "hesitation", "spontaneity", "deliberation",
  "impulsiveness", "restraint", "abandon", "inhibition", "liberation",
  "constraint", "confinement", "freedom", "captivity", "release",
  // relations between things
  "hierarchy", "equality", "parity", "disparity", "asymmetry",
  "reciprocity", "mutuality", "dependency", "autonomy",
  "interdependence", "isolationism", "cooperation", "competition",
  "collaboration", "rivalry", "alliance", "coalition", "faction",
  "schism", "unity", "division", "polarisation", "consensus",
  "dissent", "conformity", "deviance", "orthodoxy", "heresy",
  "tradition", "innovation", "convention", "rebellion",
  "compliance", "defiance", "obedience", "authority", "legitimacy",
  "power", "influence", "leverage", "coercion", "persuasion",
  "manipulation", "negotiation", "concession", "ultimatum",
  "stalemate", "impasse", "breakthrough", "resolution", "settlement",
  // knowledge and its limits
  "certainty", "doubt", "scepticism", "credulity", "belief",
  "disbelief", "suspension", "presumption", "supposition", "conjecture",
  "speculation", "inference", "deduction", "induction", "abduction",
  "premise", "conclusion", "syllogism", "fallacy", "sophistry",
  "rhetoric", "dialectic", "debate", "argument", "counterargument",
  "rebuttal", "concession", "qualification", "caveat", "proviso",
  "nuance", "subtlety", "distinction", "conflation",
  "equivocation", "ambiguity", "precision", "vagueness",
  "abstraction", "concretion", "generalisation", "specificity",
  "universality", "particularity", "exception", "anomaly", "norm",
  // the human story
  "birth", "childhood", "adolescence", "adulthood", "middle age",
  "old age", "mortality", "legacy", "inheritance",
  "lineage", "ancestry", "descent", "heritage", "custom",
  "ritual", "rite of passage", "initiation", "graduation",
  "milestone", "anniversary", "commemoration", "remembrance",
  "mourning", "eulogy", "obituary", "epitaph", "memorial", "monument",
  "archive", "chronicle", "testimony", "witness", "record", "erasure",
  "forgetting", "revisionism", "nostalgia", "retrospect",
  "foresight", "hindsight", "prescience", "premonition",
  // society writ large
  "civilisation", "culture", "subculture", "counterculture",
  "mainstream", "underground", "avant garde", "zeitgeist", "movement",
  "reform", "regression", "progress", "decline",
  "renaissance", "enlightenment", "industrialisation",
  "urbanisation", "migration", "displacement", "settlement",
  "colonisation", "decolonisation", "emancipation", "suffrage",
  "franchise", "representation", "governance", "stewardship",
  "custodianship", "trusteeship", "philanthropy", "altruism",
  "self interest", "enlightened interest", "civic duty", "public service",
  "common good", "private gain", "externality", "spillover",
  "collective action", "coordination", "mobilisation", "activism",
  "advocacy", "solidarity", "allyship", "resistance", "compliance",
  // inner architecture
  "temperament", "disposition", "character", "personality", "persona",
  "facade", "veneer", "pretence", "authenticity", "sincerity",
  "insincerity", "duplicity", "transparency", "opacity",
  "openness", "guardedness", "reserve", "reticence", "loquacity",
  "introspection", "self reflection", "self deception", "self awareness",
  "blind spot", "projection", "transference", "rationalisation",
  "justification", "excuse", "accountability", "responsibility",
  "culpability", "blame", "absolution", "exoneration", "vindication",
  "reputation", "standing", "esteem", "regard", "disregard",
];
