/** ULTRA, part two — more one and two word abstractions. */
export const ULTRA2: string[] = [
  // qualities and judgements
  "ambiguity", "certainty", "uncertainty", "clarity", "obscurity",
  "subtlety", "exaggeration", "precision", "accuracy", "consistency",
  "reliability", "credibility", "plausibility", "legitimacy", "validity",
  "relevance", "significance", "priority", "urgency", "importance",
  "necessity", "luxury", "abundance", "scarcity", "surplus", "deficit",
  "balance", "imbalance", "excess", "moderation", "restraint",
  "indulgence", "extravagance", "frugality", "thrift", "waste",
  "productivity", "output", "input", "throughput",
  "capacity", "bandwidth", "bottleneck", "throughline", "momentum",
  // society and institutions
  "tradition", "custom", "ritual", "ceremony", "etiquette", "protocol",
  "convention", "norm", "taboo", "superstition", "folklore", "mythology",
  "legend", "fable", "parable", "allegory", "satire", "parody",
  "media bias", "public opinion", "moral panic",
  "witch hunt", "scapegoat", "smear campaign", "damage control",
  "spin doctor", "press release", "leak", "exclusive", "scoop",
  "front page", "editorial", "fact check", "misinformation",
  "disinformation", "conspiracy theory", "urban legend",   "common sense", "conventional wisdom", "unwritten rule", "loophole",
  "technicality", "precedent", "jurisdiction",   "welfare state", "public sector", "private sector", "civil service",
  "town hall", "grassroots", "lobbying", "vested interest",
  "conflict of interest", "revolving door", "old boys club",
  // knowledge and learning
  "expertise", "apprenticeship", "deliberate practice", "lifelong learning",
  "unlearning", "relearning", "photographic memory",
  "forgetfulness", "false memory", "memory lane", "flashback",
  "stream of consciousness", "free association", "word association",
  "brain teaser", "riddle", "trick question", "rhetorical question",
  "logic puzzle", "process of elimination", "cause and effect",
  "correlation", "causation", "hypothesis", "experiment", "trial and error",
  "control group", "sample size", "replication",
  "reproducibility", "falsifiable", "occams razor", "straw man",
  "false dichotomy", "appeal to authority", "bandwagon", "anchoring",
  "framing effect", "loss aversion", "endowment effect", "sunk cost",
  "status quo", "optimism bias", "planning fallacy", "dunning kruger",
  "curse of knowledge", "expert blindness", "beginners mind",
  // inner life
  "solitude", "loneliness", "isolation", "belonging", "kinship",
  "camaraderie", "fellowship", "companionship", "intimacy", "distance",
  "detachment", "attachment", "dependence", "independence",
  "interdependence", "autonomy", "agency", "empowerment", "helplessness",
  "self esteem", "self worth",
  "self image", "body image", "perfectionism", "procrastination",
  "overthinking", "daydream", "wishful thinking", "false hope",
  "blind optimism", "healthy skepticism", "cynicism", "idealism",
  "realism", "pragmatism", "stoicism", "minimalism", "maximalism",
  "escapism", "avoidance", "confrontation", "acceptance",
  "surrender", "perseverance", "grit", "tenacity", "determination",
  "devotion", "reverence", "awe", "wonder",
  "fascination", "infatuation",
  "admiration", "respect", "contempt", "disdain", "indifference",
  "apathy", "enthusiasm", "zeal", "passion", "drive", "hunger",
  // change and motion
  "transition", "transformation", "reinvention",   "disruption", "innovation", "invention",
  "refinement", "regression", "stagnation",
  "acceleration", "deceleration", "drift", "trajectory",
  "trend", "fad", "cycle", "season", "cadence", "pace",
  "escalation",   "expansion", "contraction", "growth", "decline", "boom", "bust",
  "collapse", "rebound", "resurgence", "renaissance",
  "revival", "renewal", "decay", "corrosion",
  "degradation", "obsolescence",   // perception
  "perspective", "point of view", "worldview", "lens", "framing",
  "context", "subtext", "undertone", "connotation", "denotation",
  "impression", "perception", "misperception", "illusion", "delusion",
  "hallucination", "apparition", "phantom", "afterimage",
  "blur", "focus", "depth", "proximity",   "foreground", "background", "silhouette",
  "outline", "contour", "texture", "pattern", "repetition", "variation",
  "contrast", "unity", "fragmentation", "juxtaposition",
];
