/** ULTRA, part five. Pure abstractions, one or two words. */
export const ULTRA5: string[] = [
  // shape of thought
  "logic", "reason", "intuition", "instinct", "impulse", "whim",
  "caprice", "fancy", "notion", "concept", "idea", "ideal", "archetype",
  "prototype", "paradigm", "framework", "structure", "system", "model",
  "map", "territory", "blueprint", "template", "pattern", "algorithm",
  "heuristic", "shortcut", "workaround", "kludge", "elegance",
  "parsimony", "economy", "brevity", "verbosity", "digression",
  "tangent", "aside", "footnote", "preamble", "epilogue", "prologue",
  "synopsis", "gist", "essence", "substance", "form", "content",
  "surface", "depth", "layer", "stratum", "core", "periphery",
  "centre", "margin", "edge", "boundary line", "frontier", "horizon",
  // mathematics of life
  "sum", "difference", "product", "quotient", "remainder", "fraction",
  "ratio", "percentage", "average", "median", "mode", "range",
  "variance", "deviation", "spread", "cluster", "gap", "overlap",
  "intersection", "union", "subset", "superset", "sequence",
  "series", "progression", "recursion", "iteration", "convergence",
  "divergence", "limit", "asymptote", "infinity", "zero", "unity",
  "duality", "trinity", "multiplicity", "singularity", "plurality",
  // senses as ideas
  "silence", "stillness", "motion", "vibration", "resonance",
  "reverberation", "muffled", "muted", "amplified", "distorted",
  "faded", "vivid", "vibrant", "muted tone", "saturated", "washed out",
  "translucent", "transparent", "opaque", "reflective", "matte",
  "glossy", "coarse", "smooth", "rough", "brittle", "supple",
  "rigid", "elastic", "malleable", "viscous", "fluid", "solid state",
  "gaseous", "molten", "frozen", "thawed", "evaporated", "distilled",
  // human systems
  "protocol", "procedure", "process", "workflow", "pipeline",
  "checklist", "standard", "specification", "requirement", "constraint",
  "assumption", "dependency", "interface", "contract",
  "agreement", "understanding", "misunderstanding", "miscommunication",
  "crossed wires", "mixed signals", "wrong end", "lost in translation",
  "context collapse", "tone deaf", "read the room", "social cue",
  "unspoken", "implied", "inferred", "assumed", "taken for granted",
  "overlooked", "underestimated", "overestimated", "misjudged",
  "miscalculated", "mistimed", "misplaced", "misdirected", "misled",
  // states of a plan
  "intention", "ambition", "aspiration", "goal", "objective",
  "target", "quota", "deadline", "schedule",
  "timetable", "agenda", "priority", "backlog", "queue",
  "waiting list", "shortlist", "long list", "final cut", "rejection",
  "acceptance", "approval", "rubber stamp", "veto",
  "override", "escalation", "delegation", "abdication",
  "handover", "succession", "continuity", "transition",
  "interregnum", "vacancy", "placeholder", "stopgap", "interim",
  "provisional", "permanent", "temporary", "indefinite", "open ended",
  // being human, quietly
  "routine", "ritualise", "habit", "compulsion", "addiction",
  "withdrawal", "relapse", "recovery", "abstinence", "indulgence",
  "moderation", "excess", "balance", "burnout",
  "rest", "recuperation", "renewal", "reinvention",
  "reckoning", "accounting", "stocktake", "inventory", "audit",
  "reflection", "review", "appraisal", "critique",
  "self critique", "self doubt", "self belief", "self respect",
  "self reliance", "dependence", "codependence", "boundary",
  "limit", "capacity", "tolerance", "threshold",
  "breaking point", "resilience", "recovery time",
];
