/** ULTRA, part four. Pure abstractions, one or two words. */
export const ULTRA4: string[] = [
  // aesthetics and taste
  "beauty", "ugliness", "elegance", "kitsch", "camp", "minimalism",
  "maximalism", "ornament", "austerity", "opulence", "restraint",
  "excess", "proportion", "composition", "balance",
  "tension", "release", "contrast", "harmony", "discord",
  "rhythm", "cadence", "texture", "grain", "patina", "sheen",
  "craftsmanship", "workmanship", "finish", "polish", "roughness",
  "imperfection", "wabi sabi", "symmetry", "asymmetry",
  "negative space", "focal point", "vanishing point", "perspective",
  "foreshortening", "depth of field", "framing", "cropping",
  "juxtaposition", "repetition", "variation", "motif",
  "leitmotif", "refrain", "theme", "counterpoint", "improvisation",
  // ethics
  "duty", "obligation", "entitlement", "desert", "merit",
  "fairness", "impartiality", "favouritism", "bias", "prejudice",
  "discrimination", "equity", "restitution", "reparation",
  "retribution", "rehabilitation", "deterrence", "clemency", "mercy",
  "severity", "leniency", "proportionality", "necessity",
  "consent", "coercion", "autonomy", "paternalism", "beneficence",
  "harm", "negligence", "recklessness", "intent", "motive",
  "complicity", "collusion", "conflict", "loyalty", "treachery",
  "honour", "disgrace", "scandal", "cover up", "whistleblowing",
  "confidentiality", "disclosure", "candour", "deception",
  "fraud", "forgery", "counterfeit", "authenticity", "provenance",
  // mind and feeling
  "attention", "distraction", "absorption", "immersion", "detachment",
  "mindfulness", "rumination", "obsession", "compulsion",
  "aversion", "attraction", "ambivalence", "indecision", "commitment",
  "anticipation", "dread", "apprehension", "trepidation",
  "foreboding", "relief", "release", "catharsis", "closure",
  "resentment", "bitterness", "spite", "malice", "benevolence",
  "compassion", "sympathy", "pity", "condescension", "respect",
  "reverence", "contempt", "disgust", "revulsion",
  "fascination", "curiosity", "wonder", "awe",
  "astonishment", "bewilderment", "perplexity", "clarity",
  "insight", "epiphany", "revelation", "realisation", "recognition",
  "misrecognition", "projection", "empathy", "alienation",
  // time and possibility
  "simultaneity", "sequence", "duration", "interval", "frequency",
  "recurrence", "periodicity", "seasonality", "cyclicality", "linearity",
  "acceleration", "deceleration", "stasis", "momentum",
  "trajectory", "inevitability", "contingency", "possibility",
  "probability", "improbability", "impossibility", "necessity",
  "potentiality", "actuality", "latency", "emergence",
  "anticipation", "retrospection", "prospect", "hindsight",
  "foresight", "prediction", "forecast", "projection",
  "extrapolation", "scenario", "counterfactual", "alternative",
  "what if", "might have been", "missed chance", "path not taken",
  // society and exchange
  "reciprocity", "obligation", "gift", "debt", "credit",
  "trust", "distrust", "reputation", "standing", "status",
  "prestige", "stigma", "belonging", "exclusion", "inclusion",
  "assimilation", "integration", "segregation", "diaspora",
  "kinship", "community", "neighbourhood", "commons", "enclosure",
  "privatisation", "nationalisation", "regulation", "deregulation",
  "monopoly", "oligopoly", "cartel", "competition", "collusion",
  "arbitrage", "speculation", "hoarding", "scarcity",
  "abundance", "rationing", "allocation", "distribution",
  "redistribution", "subsidy", "tariff", "quota", "embargo", "sanction",
  // information
  "signal", "noise", "clarity", "distortion", "compression", "redundancy",
  "encryption", "decryption", "cipher", "code", "protocol", "handshake",
  "latency", "throughput", "bandwidth", "saturation",
  "congestion", "packet loss", "checksum", "verification", "validation",
  "authentication", "authorisation", "provenance", "attribution",
  "citation", "plagiarism", "paraphrase", "summary", "abstract",
  "index", "catalogue", "taxonomy", "ontology", "schema", "metadata",
  "annotation", "footnote", "marginalia", "erratum", "addendum",
  // scale of feeling
  "intensity", "subtlety", "magnitude", "gradation", "nuance",
  "extremity", "moderation", "excess", "deficiency", "sufficiency",
  "surplus", "shortfall", "threshold", "saturation point",
  "breaking point", "boiling point", "flash point", "turning point",
  "watershed", "milestone", "landmark", "benchmark", "baseline",
  "yardstick", "touchstone", "litmus test", "acid test", "trial",
  "ordeal", "gauntlet", "crucible", "proving ground", "rite",
];
